// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'br'
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	tabs: {
		/**
		 * A​b​o​u​t
		 */
		about: string
		/**
		 * S​k​i​l​l​s
		 */
		skills: string
		/**
		 * P​r​o​j​e​c​t​s
		 */
		projects: string
		/**
		 * C​o​n​t​a​c​t​ ​m​e
		 */
		'contact-me': string
	}
	/**
	 * H​i​,
	 */
	hi: string
	/**
	 * {​0​}
	 * @param {unknown} 0
	 */
	link: RequiredParams<'0'>
	/**
	 * I​'​m​ ​S​a​r​a​h​,
	 */
	presentation: string
	/**
	 * I​ ​a​m​ ​p​a​s​s​i​o​n​a​t​e​ ​a​b​o​u​t​ ​c​o​d​i​n​g​,​ ​I​ ​h​a​v​e​ ​a​ ​t​e​c​h​n​i​c​a​l​ ​d​i​p​l​o​m​a​ ​i​n​ ​c​o​m​p​u​t​i​n​g​ ​f​o​r​ ​t​h​e​ ​i​n​t​e​r​n​e​t​ ​a​n​d​ ​I​'​m​ ​c​u​r​r​e​n​t​l​y​ ​s​t​u​d​y​i​n​g​ ​c​o​m​p​u​t​e​r​ ​s​c​i​e​n​c​e​.
	 */
	subheading: string
	/**
	 * R​e​s​u​m​e
	 */
	resume: string
	/**
	 * E​m​a​i​l​ ​m​e
	 */
	email: string
}

export type TranslationFunctions = {
	tabs: {
		/**
		 * About
		 */
		about: () => LocalizedString
		/**
		 * Skills
		 */
		skills: () => LocalizedString
		/**
		 * Projects
		 */
		projects: () => LocalizedString
		/**
		 * Contact me
		 */
		'contact-me': () => LocalizedString
	}
	/**
	 * Hi,
	 */
	hi: () => LocalizedString
	/**
	 * {0}
	 */
	link: (arg0: unknown) => LocalizedString
	/**
	 * I'm Sarah,
	 */
	presentation: () => LocalizedString
	/**
	 * I am passionate about coding, I have a technical diploma in computing for the internet and I'm currently studying computer science.
	 */
	subheading: () => LocalizedString
	/**
	 * Resume
	 */
	resume: () => LocalizedString
	/**
	 * Email me
	 */
	email: () => LocalizedString
}

export type Formatters = {}
