name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.5.1
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: build
        env:
          BASE_PATH: '/sarassaura.github.io'
          GITHUB: ${{ secrets.GITHUB }}
          VITE_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{ secrets.VITE_PUBLIC_CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_URL: ${{ secrets. CLOUDINARY_URL }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        run: |
          npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1